version: '3.9'

services:
  postgres:
    container_name: rad_estacio
    image: postgres:latest
    environment:
      POSTGRES_DB: ets_ufpb_rad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gerenciador_network

volumes:
  postgres_data:

networks:
  gerenciador_network: